spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    testOnBorrow: true
    validationQuery: SELECT 1

doma:
  naming: SNAKE_LOWER_CASE
  dialect: postgres

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: '${SECURITY_OAUTH2_CLIENT_CLIENTID}' # Slackのアプリケーション登録で表示された「Client ID」
      clientSecret: '${SECURITY_OAUTH2_CLIENT_CLIENTSECRET}' # Slackのアプリケーション登録で表示された「Client Secret」
      accessTokenUri: 'https://slack.com/api/oauth.access' # Slackを利用する場合の設定値
      userAuthorizationUri: 'https://slack.com/oauth/authorize?team=ahrin' # Slackを利用する場合の設定値
      authenticationScheme: 'query' # Slackを利用する場合の設定値
      scope: 'identify' # Slackを利用する場合の設定値
      tokenName: 'token' # Slackを利用する場合の設定値
    resource:
      userInfoUri: 'https://slack.com/api/auth.test' # Slackを利用する場合の設定値