CREATE TABLE music_result_dbhr (
    id SERIAL,
    user_name 						VARCHAR(100),
    name							VARCHAR(100),
    nha								VARCHAR(15),
    clear_lamp						VARCHAR(30),
    ex_score						INTEGER,
    bp								INTEGER,
    score_rank						VARCHAR(6),
    score_rate						NUMERIC,
    miss_rate						NUMERIC,
    tag								VARCHAR(200),
    fav								VARCHAR(200),
    clear_lamp_DBR					VARCHAR(30),
    clear_lamp_DBRR					VARCHAR(30),
    clear_lamp_DBM					VARCHAR(30),
    clear_lamp_DBSR					VARCHAR(30),
    clear_lamp_DBM_NONAS			VARCHAR(30),
    clear_lamp_RH					VARCHAR(30),
    clear_lamp_LH					VARCHAR(30),
    my_difficult					NUMERIC,
    dj_point						NUMERIC,
    clear_progress_rate				NUMERIC,
    last_play_date					TIMESTAMP,
    last_update_date				TIMESTAMP,
    remaining_gauge_or_dead_notes	INTEGER,
    memo_other						VARCHAR(200),
    p_great							VARCHAR(6),
    great							VARCHAR(6),
    good							VARCHAR(6),
    bad								VARCHAR(6),
    poor							VARCHAR(6),
    combo_break						VARCHAR(6),
    ins_date						TIMESTAMP,
    upd_date						TIMESTAMP,
    PRIMARY KEY (user_name, name, nha)
);